--- #YAML:1.0
name: Heliotrope
abstract: An integrated clinical genomics application
version: 0.10
author:
  - Stuart Watt <stuart@morungos.com>
license: gpl3
distribution_type: script
requires:
  Config: 0
  Config::Any: 0
  Cwd: 0
  boolean: 0
  common::sense: 0
  Bio::DB::Fasta: 0
  CHI: 0
  Clone: 0
  Convert::Scalar: 0
  DBI: 0
  DBD::SQLite: 0
  Data::Dump: 0
  Data::GUID: 0
  DateTime: 0
  DateTime::Format::Natural: 0
  DateTime::Tiny: 0
  Exporter::Easy: 0
  File::HomeDir: 0
  File::Slurp: 0
  Graph: 0
  HTTP::Request: 0
  IO::CaptureOutput: 0
  JSON: 0
  Lingua::Stem::Snowball: 0
  Lingua::StopWords: 0
  List::MoreUtils: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  Log::Any::Adapter::Log4perl: 0
  Log::Log4perl: 0
  MongoDB: 0
  Moose: 0
  MooseX::Singleton: 0
  PDL: 0
  Parallel::ForkManager: 0
  Spreadsheet::ParseExcel: 0
  Sub::Exporter: 0
  Text::CSV: 0
  Text::Unidecode: 0
  Tie::IxHash: 0
  Try::Tiny: 0
  URI::Escape::XS: 0
  URI: 0
  WWW::Mechanize: 0
  XML::LibXML: 0
  perl: 5.014_00
recommends:
  JSON::XS: 0
build_requires:
  Test: 0
resources:
  repository: https://github.com/oicr-ibc/heliotrope
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
