---
# file: packaging.yml

# This file is used to prepare a Debian package for the web application.
# It is significantly different to the normal deployment process, because
# the locations can be different. Also, there are fewer dependencies
# needed, since we don't want a live system.

- hosts: all
  sudo: True
  tasks:
    setup:
      filter: '*'

- hosts: all
  sudo: True
  vars:
    mongodb_server: '_DBC_DBSERVER_'
    mongodb_port: '_DBC_DBPORT_'
    mongodb_name: '_DBC_DBNAME_'
    mongodb_user: '_DBC_DBUSER_'
    mongodb_password: '_DBC_DBPASS_'
  tasks:
    - name: Packaging | Installing required packages
      apt: pkg={{ item.package }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - { package: 'build-essential' }
        - { package: 'devscripts' }
        - { package: 'debhelper' }

    - name: Packaging | Create directories
      shell: mkdir -p {{ item.path }} creates={{ item.path }}
      with_items:
        - { path: '/usr/lib/heliotrope' }
        - { path: '/usr/lib/heliotrope/etc/reporting' }
        - { path: '/tmp/heliotrope-packaging' }
        - { path: '/tmp/heliotrope-packaging/usr/lib' }
        - { path: '/tmp/heliotrope-packaging/debian' }
        - { path: '/tmp/heliotrope-packaging/etc/heliotrope' }

    - name: Packaging | Get nodejs
      get_url:
        dest: '/tmp/node-latest.tar.gz'
        url: 'http://nodejs.org/dist/node-latest.tar.gz'

    - name: Packaging | Create directory
      command: mkdir -p node-latest-install chdir=/tmp creates=/tmp/node-latest-install

    - name: Packaging | Unpack nodejs
      command: tar -x -z --strip-components=1 -f /tmp/node-latest.tar.gz chdir=/tmp/node-latest-install creates=/tmp/node-latest-install/configure

    - name: Packaging | Configure nodejs
      command: ./configure --shared-openssl --shared-zlib --prefix=/usr/lib/heliotrope/node chdir=/tmp/node-latest-install creates=/tmp/node-latest-install/config.mk

    - name: Packaging | Build nodejs
      command: make chdir=/tmp/node-latest-install creates=/tmp/node-latest-install/out/Release/node

    - name: Packaging | Install nodejs
      command: make install chdir=/tmp/node-latest-install creates=/usr/lib/heliotrope/node

    - name: Packaging | Copy files
      synchronize:
        src: './dist/'
        dest: '/usr/lib/heliotrope'
        rsync_path: 'sudo rsync'

    - name: Packaging | Copy reporting files
      synchronize:
        src: './etc/reporting/'
        dest: '/usr/lib/heliotrope/etc/reporting'
        rsync_path: 'sudo rsync'

    - name: Packaging | Install nodejs packages
      command: /usr/lib/heliotrope/node/bin/npm install --production chdir=/usr/lib/heliotrope creates=/usr/lib/heliotrope/node_modules

    - name: Packaging | Set nodejs module binary execute permissions
      command: find -name '*.node' -exec chmod 0644 {} \; chdir=/usr/lib/heliotrope/node_modules

    - name: Packaging | Remove nodejs module CVS files
      command: find -name '.git*' -exec rm {} \; chdir=/usr/lib/heliotrope/node_modules

# At this stage, we have a complete layout, with components installed in the
# correct places and a complete node.js with all its production dependencies
# correctly in place. That means we can now synchronize this to a packaging
# location and assemble the Debian.

    - name: Packaging | Assemble files
      command: rsync -av {{ item.src }} {{ item.dest }}
      with_items:
        - { src: '/usr/lib/heliotrope/', dest: '/tmp/heliotrope-packaging/usr/lib/heliotrope' }

    - name: Packaging | Copy upstart configuration file
      template: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: 'roles/webapp/templates/upstart-heliotrope.conf.j2', dest: '/tmp/heliotrope-packaging/debian/heliotrope.upstart' }

# Template the JSON config file. This time, we use special placeholders that are replaced by
# the Debian package installation scripts. The only proviso is that a username and password
# which are empty should be removed from the URLs.

    - name: Packaging | Copy heliotrope configuration file
      template: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: 'roles/webapp/templates/heliotrope-config.json.j2', dest: '/tmp/heliotrope-packaging/etc/heliotrope/config.json' }

    - name: Packaging | Get packaging files
      synchronize:
        src: './etc/debian/'
        dest: '/tmp/heliotrope-packaging/debian'
        rsync_path: 'sudo rsync'

    - name: Packaging | Discover the package.json contents
      shell: cat /usr/lib/heliotrope/package.json
      register: package_json

    - name: Packaging | Register the package version
      shell: "{% set package_json_data = package_json.stdout|from_json %}echo {{package_json_data['version']}}"
      register: package_version

# debuild is extremely sensitive about the date format. I'd recommend you don't change
# it unless you know what you're doing.

    - name: Packaging | Discover the git commit date
      sudo: False
      local_action: command git log -n 1 --pretty=format:'%aD'
      register: git_log_date

    - name: Packaging | Get packaging files
      template:
        src: ./etc/debian-templates/changelog
        dest: /tmp/heliotrope-packaging/debian/changelog


    - name: Packaging | Build the package
      command: "debuild -b -us -uc chdir=/tmp/heliotrope-packaging creates=/tmp/heliotrope_{{package_version.stdout}}_amd64.deb"

    - name: Packaging | Get the Debian package back
      synchronize:
        mode: pull
        dest: './.tmp/'
        src: "/tmp/heliotrope_{{package_version.stdout}}_amd64.deb"
        rsync_path: 'sudo rsync'