---
- name: Webapp | Create directories
  shell: mkdir -p {{ item.path }} creates={{ item.path }}
  with_items:
    - { path: '/usr/lib/heliotrope' }
    - { path: '/var/log/heliotrope' }
    - { path: '/var/run/heliotrope' }
    - { path: '/usr/lib/heliotrope/etc/reporting' }
    - { path: '/etc/heliotrope' }

- name: Webapp | Copy files
  synchronize:
    src: './dist/'
    dest: '/usr/lib/heliotrope'
    rsync_path: 'sudo rsync'

- name: Webapp | Copy reporting files
  synchronize:
    src: './etc/reporting/'
    dest: '/usr/lib/heliotrope/etc/reporting'
    rsync_path: 'sudo rsync'

- name: Webapp | Install dependencies
  command: npm install --production chdir=/usr/lib/heliotrope

- name: Webapp | Write configuration files
  template: src={{ item.src }} dest={{ item.dest }}
  notify:
    - restart heliotrope
  with_items:
    - { src: 'heliotrope-config.j2', dest: '/etc/heliotrope/config.json' }
    - { src: 'heliotrope-upstart.j2', dest: '/etc/init/heliotrope.conf' }

- name: Webapp | Create user heliotrope
  user: name=heliotrope comment="heliotrope webapp" state=present

- name: Webapp | Assign files to the heliotrope user
  file: path={{ item.path }} recurse=yes owner=heliotrope group=adm mode=0750
  with_items:
    - { path: '/var/log/heliotrope' }
    - { path: '/var/run/heliotrope' }


- name: Webapp | Ensure heliotrope is running
  service: name=heliotrope state=started
